/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Catalog */
        get: operations["search_catalog_api_v1_catalog_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/application/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Application Status */
        get: operations["application_status_api_v1_application_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/posters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Catalog Posters */
        post: operations["catalog_posters_api_v1_catalog_posters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommendations */
        post: operations["recommendations_api_v1_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/refinements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refinements */
        post: operations["refinements_api_v1_refinements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationStatus */
        ApplicationStatus: {
            /** Backend Mode */
            backend_mode: string;
            /** Model Label */
            model_label: string;
            /** Data Source Label */
            data_source_label: string;
            /** Refinement Available */
            refinement_available: boolean;
            /**
             * Poster Provider
             * @default tmdb
             * @constant
             */
            poster_provider: "tmdb";
            /** Posters Configured */
            posters_configured: boolean;
            /** Available Genres */
            available_genres: string[];
        };
        /** AppliedRefinement */
        AppliedRefinement: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "applied";
            /** Preference Revision */
            preference_revision: number;
            preferences: components["schemas"]["PreferenceState"];
            /** Summary */
            summary: string;
        };
        /** CatalogMovie */
        CatalogMovie: {
            /** Movie Id */
            movie_id: string;
            /** Title */
            title: string;
            /** Genres */
            genres?: string[];
            /** Poster Url */
            poster_url?: string | null;
        };
        /** CatalogSearchResponse */
        CatalogSearchResponse: {
            /** Items */
            items: components["schemas"]["CatalogMovie"][];
            /** Total */
            total: number;
            /** Backend Mode */
            backend_mode: string;
        };
        /** ClarificationRefinement */
        ClarificationRefinement: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "clarification";
            /** Question */
            question: string;
        };
        /** ComponentInfo */
        ComponentInfo: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "fixture" | "baseline" | "learned" | "pass_through" | "external";
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /** Issues */
            issues?: {
                [key: string]: unknown;
            }[];
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PosterMetadata */
        PosterMetadata: {
            /** Movie Id */
            movie_id: string;
            /** Tmdb Id */
            tmdb_id?: string | null;
            /** Poster Url */
            poster_url?: string | null;
            /** Backdrop Url */
            backdrop_url?: string | null;
            /** Backdrop Url Small */
            backdrop_url_small?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "missing" | "unavailable";
        };
        /** PosterRequest */
        PosterRequest: {
            /** Movie Ids */
            movie_ids: string[];
        };
        /** PosterResponse */
        PosterResponse: {
            /** Items */
            items: components["schemas"]["PosterMetadata"][];
            /**
             * Provider
             * @default tmdb
             * @constant
             */
            provider: "tmdb";
            /** Configured */
            configured: boolean;
        };
        /** PreferenceState */
        PreferenceState: {
            /** History Items */
            history_items?: string[];
            /** Excluded Movie Ids */
            excluded_movie_ids?: string[];
            /** Include Genres */
            include_genres?: string[];
            /** Exclude Genres */
            exclude_genres?: string[];
        };
        /** RecommendationItem */
        RecommendationItem: {
            /** Rank */
            rank: number;
            movie: components["schemas"]["CatalogMovie"];
            /** Retrieval Score */
            retrieval_score?: number | null;
            /** Ranking Score */
            ranking_score?: number | null;
        };
        /** RecommendationRequest */
        RecommendationRequest: {
            /** Session Id */
            session_id: string;
            /** Preference Revision */
            preference_revision: number;
            preferences: components["schemas"]["PreferenceState"];
            /**
             * Result Count
             * @default 12
             */
            result_count: number;
            /** Known User Id */
            known_user_id?: string | null;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Request Id */
            request_id: string;
            /** Preference Revision */
            preference_revision: number;
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationItem"][];
            applied_preferences: components["schemas"]["PreferenceState"];
            retrieval: components["schemas"]["ComponentInfo"];
            reranker: components["schemas"]["ComponentInfo"];
            /** Backend Mode */
            backend_mode: string;
            /** Partial */
            partial: boolean;
            /** Warnings */
            warnings: string[];
            timings: components["schemas"]["Timings"];
        };
        /** RefinementRequest */
        RefinementRequest: {
            /** Session Id */
            session_id: string;
            /** Preference Revision */
            preference_revision: number;
            preferences: components["schemas"]["PreferenceState"];
            /** Text */
            text: string;
        };
        /** StatusResponse */
        StatusResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "not_ready";
            /** Backend Mode */
            backend_mode: string;
            /** Detail */
            detail?: string | null;
        };
        /** Timings */
        Timings: {
            /** Retrieval Ms */
            retrieval_ms: number;
            /** Filtering Ms */
            filtering_ms: number;
            /** Reranking Ms */
            reranking_ms: number;
            /** Total Ms */
            total_ms: number;
        };
        /** UnavailableRefinement */
        UnavailableRefinement: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "unavailable";
            /** Message */
            message: string;
        };
        /** UnsupportedRefinement */
        UnsupportedRefinement: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "unsupported";
            /** Message */
            message: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    search_catalog_api_v1_catalog_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    application_status_api_v1_application_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationStatus"];
                };
            };
        };
    };
    catalog_posters_api_v1_catalog_posters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PosterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommendations_api_v1_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refinements_api_v1_refinements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefinementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppliedRefinement"] | components["schemas"]["ClarificationRefinement"] | components["schemas"]["UnsupportedRefinement"] | components["schemas"]["UnavailableRefinement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
